M48
; DRILL file {KiCad (6.0.6)} date Mon Aug 15 20:08:06 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-15T20:08:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0469
%
G90
G05
T1
X4.625Y-3.25
X4.625Y-3.55
X4.725Y-3.25
X4.725Y-3.55
X5.125Y-3.25
X5.125Y-3.55
T2
X4.5Y-3.2
X4.5Y-3.6
T3
X5.5Y-3.2
X5.5Y-3.3
X5.5Y-3.4
X5.5Y-3.5
X5.5Y-3.6
T0
M30
